# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


defaults:
  run:
    working-directory: ./luukitup

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - name: CI
      run: npm ci
    - name: Build
      run: npm run build
    #- name: install forever
    #  run: npm install forever -g
    
    - name: Running Test
      run: npm test
    - name: Start App
      run: npm start:ci &
    - name: Running E2E Cypress Tests
      run: npm run test:e2e
      
    #- name: Start App
    #  run: forever start -c "npm run serve" ./
    #- name: Sleep for 30 seconds (Let the app boot)
    #  uses: jakejarvis/wait-action@master
    #  with:
    #    time: '30s'
    #- name: Running E2E Cypress Tests
    #  run: npx cypress run --key ${{secrets.cypress_id}}
      
    # start the server in the background
    #- npm run start:ci &
    # run Cypress tests
    #- npm run e2e

    - name: Archive production artifact
      uses: actions/upload-artifact@main
      with:
        name: dist
        path: luukitup/dist
              
  deploy-owndomain:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Download artifact
        uses: actions/download-artifact@main
        with:
          name: dist
          path: luukitup/dist
      - name: Deploy to luukitup.nl
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 185.182.57.39
          username: CICD@luukitup.nl
          password: ${{secrets.ftp_password}}
          server-dir: public_html/
          local-dir: ./luukitup/dist/
